language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="core.settings.travis"

services:
  - postgresql

script:
  - python manage.py test

dist: xenial

addons:
  chrome: stable

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮