language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="core.settings.travis"

services:
  - postgresql

addons:
  chrome: stable

before_install:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - python manage.py test
