# Generated by Django 3.2.2 on 2021-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_post',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
