# Generated by Django 3.2.2 on 2021-05-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210510_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contenu',
            new_name='detail',
        ),
    ]
