# Generated by Django 3.2.2 on 2021-05-11 12:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=tinymce.models.HTMLField(),
        ),
    ]
